apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app
  namespace: gsus-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      name: register-app
      labels:
        app: register-app
    spec:
      revisionHistoryLimit: 0
      containers:
        - name: register-app-container
          image: jesu11s/kubernetes-course:register-app-0.0.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: register-svc
  namespace: gsus-ns
spec:
  type: ClusterIP
  selector:
    app: register-app
  ports:
    - port: 80
      targetPort: 80
